# runMacro.sub
universe = vanilla
executable              = runMacro.sh
arguments               =

# Logs
output                  = logs/runMacro_$(Cluster)_$(Process).out
error                   = logs/runMacro_$(Cluster)_$(Process).err
log                     = logs/runMacro_$(Cluster)_$(Process).log

# Job settings
+JobFlavour             = "tomorrow"

# Put all PDF outputs in the "output/" folder
transfer_output_files   = output
when_to_transfer_output = ON_EXIT

queue
